version: '3.8'

services:  
  app:    
    build: .    
    ports:      
      - "8181:8181"    
    volumes:      
      - .:/app
      - ./storage:/app/storage
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash -c "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8181"
  
  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6379:6379"

  worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: php artisan queue:work redis